- setup.cfg
The [wheel] section is legacy and not required. [bdist_wheel] is enough. For additional details, see:
https://github.com/pypa/wheel/blob/3dc261abc98a5e43bc7fcf5783d080aaf8f9f0cf/wheel/bdist_wheel.py#L127-L133
http://pythonwheels.com/
> Remove redundant [wheel] section

- pyparsing.py
Fixes https://sourceforge.net/p/pyparsing/bugs/106/.
With Python 3.7, I'm getting:
```
/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:943: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
collections.MutableMapping.register(ParseResults)
/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py:3245: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
elif isinstance( exprs, collections.Iterable ):
```
This PR fixes it.
The tests pass for me on macOS High Sierra with Python 2.7 and 3.7:
```
⌂107% [hugo:/tmp/pyparsing] patch-2 ± python2 unitTests.py …
```
> Fix collections ABCs deprecation warning

- examples/searchParserAppDemo.py
__Set()__ is an _undefined name_ in this context but __set()__ is used elsewhere in this class.
[flake8](http://flake8.pycqa.org) testing of https://github.com/pyparsing/pyparsing on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./examples/searchParserAppDemo.py:15:18: F821 undefined name 'Set'
result = Set()
^
1    F821 undefined name 'Set'
1
```
> Undefined name: Set() --> set()

- unitTests.py
The _builtin_ __file()__ was removed in Python 3 so this PR advocates the use of __open()__ instead.
Also note that four lines above, __testclass__ is an _undefined name_ and perhaps __testclasses__ should be used in its place.
Undefined names have the potential to raise NameError at runtime.
[flake8](http://flake8.pycqa.org) testing of https://github.com/pyparsing/pyparsing on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./unitTests.py:3901:60: F821 undefined name 'testclass'
lp.run("testRunner.run( makeTestSuite(%s) )" % testclass.__name__)
^
./unitTests.py:3905:17: F821 undefined name 'file'
outstream = file(outfile,"w")
^
2    F821 undefined name 'testclass'
2
```
> Undefined name: file() was removed in Python 3

- MANIFEST.in
- docs/conf.py
- docs/index.rst
I am sorry, but this should be [really tested to work](https://build.opensuse.org/package/show/devel:languages:python/python-pyparsing).
> Not sure how I managed to screw up building documentation again.

- examples/holaMundo.py
- unitTests.py
The all caps "UTF-8" causes warnings or errors in some editors. "utf-8" is more widely recognized. For example, when opening files in Emacs, I see:
> Warning (mule): Invalid coding system ‘UTF-8’ is specified
> for the current buffer/file by the :coding tag.
> It is highly recommended to fix it before writing to a file.
> Really proceed with writing? (yes or no)
I'm then promped before saving.
The CPython source code uses the lowecase form.
> Fix encoding cookie to use encoding "utf-8"

- CHANGES
- setup.py
setuptools includes a vendored version of pyparsing (and other
dependencies). They are not install through traditional tools.
Therefore, distutils is not required as fallback to facilitate
setuptools.
https://github.com/pypa/setuptools/blob/v40.6.3/setuptools/_vendor/pyparsing.py
Also remove the unused imports.
> Remove distutils fallback and outdated comment

- examples/LAparser.py
- examples/antlr_grammar.py
- examples/dfmparse.py
- examples/dictExample2.py
- examples/excelExpr.py
- examples/fourFn.py
- examples/getNTPserversNew.py
- examples/idlParse.py
- examples/lucene_grammar.py
- examples/mozillaCalendarParser.py
- examples/nested.py
- examples/parseTabularData.py
- examples/pgn.py
- examples/protobuf_parser.py
- examples/pymicko.py
- examples/rangeCheck.py
- examples/searchparser.py
- examples/simpleSQL.py
- examples/sparser.py
- examples/sql2dot.py
- examples/stackish.py
- examples/stateMachine2.py
- examples/test_bibparse.py
- examples/urlExtractorNew.py
- examples/verilogParse.py
- pyparsing.py
- unitTests.py
Unused imports were discovered using flake8. By removing the unused imports, the code is a bit friendlier to new contributors as it is clearer what is being used and not simply leftover from previous
refactoring.
The flake8 command:
```
$ flake8 . --select F401
```
http://flake8.pycqa.org/
> Remove unused imports throughout project

- examples/LAparser.py
- examples/dfmparse.py
- examples/pythonGrammarParser.py
- examples/verilogParse.py
- unitTests.py
Catching all exceptions is generally considered a bad practice under most circumstances as it will also catch `KeyboardInterrupt` and `SystemExit`. These special cases should be raised to the interpreter to
allow the Python process to exit.
This fix complies with pycodestyle's error code E722:
https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes
> do not use bare except, specify exception instead
> Replace bare 'except:' with 'except Exception;'

- docs/HowToUsePyparsing.rst
- examples/verilogParse.py
- pyparsing.py
The psyco package has been declared umaintained and dead. It is no longer receiving bug fixes including for security issues. From http://psyco.sourceforge.net/
> 12 March 2012
>
> Psyco is unmaintained and dead. Please look at PyPy for the state-of-the-art in JIT compilers for Python.
Avoid recommending the use of an unmaintained package (since 2012). Users can continue to use PyPy for the latest and greatest in Python JIT.
> Remove mentions of 'psyco' from docs and examples

- pyparsing.py
- simple_unit_tests.py
This might not be too desirable with the end of life right around the corner, but the incompatibilities weren't too tricky to deal with for the purposes of simply running the suite.  Granted, the traceback sent to `explain` is probably the wrong one, and the `subTest` shim isn't fully functional, but at least the file passes.
> Support for simple_unit_tests under Python 2

- MANIFEST.in
Add examples/*.h to manifest so snmp_api.h gets packaged with the rest of the test files.
Noticed when attempting to run "python3 setup.py test" against 2.3.1 tarball.
> snmp_api.h missing from manifest

- pyparsing.py
When writing float numbers, integer part can be omitted, in which case it defaults to 0. Thus, `.123456` and `-.123456` are valid floats, equalling to 0.123456 and -0.123456, respectively. However, `pyparsing` does not support such notation. This pull request changes the quantifier of the `pyparsing_common.real` integer part regex token, adding support for such numbers.
> Support for omitted integer part of the float number

- docs/HowToUsePyparsing.rst
As part of the effort to make pyparsing more 3.X-oriented, the How To page should be updated.
This change modifies the print statements in code samples so they use 3.X compatible syntax.
`except ParseException, err` also needed to be updated.
> How-To page: 3.x-ify some print statements and an except

- examples/booleansearchparser.py
Boolean Search query parser, based on searchparser, that allows to perform searches with the common boolean search syntax against a text (western + non-western alphabets)
```
#SAMPLE USAGE:
from booleansearchparser import BooleanSearchParser
bsp = BooleanSearchParser()
text = u"wildcards at the begining of a search term "
exprs= [
u"*cards and term", #True
u"wild* and term",  #True
u"not terms",       #True
u"terms or begin",  #False
]
for expr in exprs:
print bsp.match(text,expr)
#non-western samples
text = u"안녕하세요, 당신은 어떠세요?"
exprs= [
u"*신은 and 어떠세요", #True
u"not 당신은",       #False
u"당신 or 당",  #False
]
for expr in exprs:
print bsp.match(text,expr)
```
> Boolean Search query parser: allows to perform searches with the common boolean search syntax against a text

- examples/bigquery_view_parser.py
Previously, the parser would fail when a `WINDOW` clause was in a `WITH` section.  For example, this SQL was unparseable:
```
WITH x AS (
SELECT a
FROM b
WINDOW w as (PARTITION BY a)
)
SELECT y FROM z
```
With this change, the parser handles these cases correctly
> BigQuery SQL parser: handle WINDOW clause in WITH section

- examples/bigquery_view_parser.py
BigQuery view SQL parser was failing on IGNORE NULL statements like:
```
SELECT
DISTINCT FIRST_VALUE(x IGNORE NULLS) OVER (PARTITION BY y)
FROM z
```
E.g. see doc at https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#first_value
> BigQuery View parse fails on IGNORE NULLS

- setup.py
As pyparsing is a dependency used by setuptools this allows packagers to use distutils as a fallback when bootstraping setuptools without much fuss.
The package will be built it will just render the setup.py test not working for anyone not building with setuptools, but that is just a trivial issue i would say.
> Support building without setuptools

- .travis.yml
- The default "dist" is now xenial, can remove the override.
- The "sudo" key is now deprecated and is no longer necessary.
- Python 3.8 final is now available.
> Remove unnecessary keys and overrides from Travis

- tox.ini
Allows contributors to easily run the full test matrix locally.
Python 3.8 was released on on October 14th, 2019.
https://docs.python.org/3/whatsnew/3.8.html
> Add Python 3.8 to the tox matrix

- setup.py
- pyparsing supports Python 3.8
- pyparsing is Python 3 only
- pyparsing supports PyPy in addition to CPython
The trove classifiers display on PyPI and provide quick, at-a-glance
information for library users to know if it is suitable for inclusion in
a project.
For a complete list of trove classifiers, see:
https://pypi.org/classifiers/
> Add missing trove classifiers to setup.py

- setup.cfg
As pyparsing is now Python 3 only, the wheel is not "universal". A
universal wheel is defined as:
https://wheel.readthedocs.io/en/stable/user_guide.html
> If your project contains no C extensions and is expected to work on
> both Python 2 and 3, you will want to tell wheel to produce universal
> wheels …
As the project is _not_ expected to work on Python 2, it should not be
distributed as a Python 2 wheel. Instead, it should be distributed as a
Python-3-only wheel.
> Remove 'universal = 1' from [bdist_wheel] section of setup.cfg

- examples/simpleBool.py
In Python 3, the __nonzero__ method was renamed to __bool__. It no
longer exists as a magic method.
> Py3 cleanup: Remove __nonzero__ method

- examples/btpyparse.py
- pyparsing.py
Unlink Python 2, in Python 3, `__ne__` defaults to the inverse of the
`__eq__` method. Can remove the definitions that follow this default.
From the Python docs
https://docs.python.org/3/reference/datamodel.html#object.__ne__
> By default, `__ne__()` delegates to `__eq__()` and inverts the result
> unless it is NotImplemented.
> Py3 cleanup: Remove unnecessary __ne__ method

- examples/getNTPserversNew.py
- examples/htmlStripper.py
- examples/partial_gene_match.py
- examples/urlExtractor.py
- examples/urlExtractorNew.py
In Python 3, urlopen() can always be used as a context manager. Wrapping
with closing() is not necessary.
https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen
> This function always returns an object which can work as a context
> manager …
> Py3 cleanup: Remove use of closing() with urlopen()

- examples/booleansearchparser.py
> Py3 cleanup: Remove workaround from Python3 unichr()

- examples/getNTPserversNew.py
- examples/statemachine/statemachine.py
For Python 3 only code, the import path is known and stable. Can remove
the ImportError workaround.
> Py3 cleanup: Remove workaround for Python2 urllib

- .travis.yml
- tox.ini
After commit 3481b6f3f9bb2dae7e9d88ed08989b5f71238e4b, tox failed to run
tests locally. The tox configuration now uses a command identical to
Travis. It runs the unittest test discoverer.
The command "discover" is the default if no additional argument is
passed to unittest.
> Fix tox to run refactored tests

- CHANGES
- MANIFEST.in
- setup.py
The tests are run through either tox or Travis CI. In both cases, the
setup.py "test_suite" entrypoint is not used.
Further, the use of "test_suite" is discouraged as it installs using
eggs rather than pip.
> Remove unused setup.py keywords "test_suite"

- README.rst
- setup.py
Hello,
On environments where the default encoding is set to ASCII (i.e. default Debian Stretch), installing pyparsing 2.4.4 fails with an error because README.rst contains a unicode character.
Explicitly specifying the encoding as UTF-8 fixes the problem.
> Explicitly specify UTF-8 encoding when opening README file

- examples/select_parser.py
Update for the select_parser example:
* sqlite now supports `TRUE` and `FALSE` as literal values
* use pyparsing_common for numeric expressions
* fix identifier quoting (`"`, with escaping via `""`)
* downcase identifiers unless they're quoted
* fix string quoting (escape with `''`)
* add support for sql comments (`-- comment`)
* additional test cases
One thing I would like to quite figure out is where failures for these test cases (not included here) are coming from, must be something to do with operator precedence but I can't spot where:
```
SELECT * FROM abcd WHERE ff NOT IN (1,2,4,5)
^
FAIL: Expected end of text, found 'N'  (at char 28), (line:1, col:29)
SELECT * FROM abcd WHERE ff not between 3 and 9
^
FAIL: Expected end of text, found 'n'  (at char 28), (line:1, col:29)
SELECT * …
```
> select_parser example: misc improvements

- .pre-commit-config.yaml
- pyparsing/helpers.py
- tests/README.md
- tests/requirements.txt
- tox.ini
This hook will run Black upon commit.  If something needs formatting, then the file is fixed, and the commit fails.  Commit a second time for success.  This only acts on changed files.
> Add Black formatting Git hook

- pyparsing/core.py
- tests/test_unit.py
I've written some additional unit tests and came across a potential issue with matchPreviousExpr. Can you please take a look at it and let me know if this is expected behavior?
> New unit tests

- pyparsing/testing.py
This import is currently unused in the file.
I'm looking at optimising start-up times of a project I work on, and
importing pyparsing currently takes about 82ms, which is quite a lot for
my domain. Just not importing `unittest` shaves 14ms off of that import
time.
Currently 
Before this change:
```
$ multitime -n 20 --  python3.6 -c 'import pyparsing'
===> multitime results
1: python3.6 -c "import pyparsing"
Mean        Std.Dev.    Min         Median      Max
real        0.082       0.005       0.071       0.083       0.088
user        0.066       0.004       0.056       0.067       0.071
sys         0.013       0.001       0.012       0.013       0.014
```
After this change:
```
$ multitime -n 20 --  python3.6 -c 'import pyparsing'
===> multitime results
1: python3.6 -c "import …
```
> Don't import unittest in testing.py

- pyparsing/__init__.py
- pyparsing/core.py
- pyparsing/helpers.py
- pyparsing/testing.py
- pyparsing/util.py
When I was first using pyparsing I spent a lot of time reading the documentation and noted some formatting inconsistencies.
The first commit fixes list & code blocks that aren't formatted on read the docs the way they're intended to.
The second adds missing class references and inline code formatting.
The third tries to fix a broken reference but I wasn't able to test it to see if it works. It also demos a potential formatting change that is entirely your decision. Because read the docs has such a narrow page, a lot of inline code blocks require horizontal scrolling, sometimes only for comments which can be frustrating as a reader. If you prefer the current format I'll revert those, no problem!
> Docstring formatting changes

- pyparsing/helpers.py
- tests/test_simple_unit.py
- tests/test_unit.py
A really small change but a quite useful one.
The `countedArray` helper is very nice but it assumes that the count expression is directly preceding the list. I've stumbled upon a situation where there are some extra tokens in between the count token and items in the list.
Example: There are two flags right after the count value which describe the list in some way. They can take a single ascii letter or "-".
With my change, one can do:
```python
my_array = countedArray(Word(alphanums), And([
Word(nums).setParseAction(lambda t: int(t[0])),
Group(Char(alphas + "-") * 2)
]))
print(my_array.parseString("5 a b item1 item2 item3 item4 item5"))
```
which will print:
```python
[['a', 'b'], ['item1', 'item2', 'item3', 'item4', 'item5']]
```
This doesn't change a normal behaviour of `countedArray` …
> Pop counter token and return rest instead of dropping all tokens in countedArray

- tests/test_unit.py
These tests focus on previously uncovered paths. Two behaviors surprised me, though these are edge cases:
1. When a type other than ParserElement or string is used in any of the expressions (I use int as a test case) a warning is issued and the entire expr is set to None. This will later throw a ParseError when the expr is parsed because a None type can't be parsed.
2. When using type string with the & operator, it seems that can be parsed successfully provided they are in the order of the string being parsed, but not if they're out of order.
Both of these may be expected behavior, just thought I'd share.
> Parser Element and Keyword tests

- tests/test_unit.py
There are a bunch of imports in the unit tests that import pyparsing elements, some of which are exploded onto many lines by black. It seems unnecessary, since they can all be referenced with pp, ie `pp.Word`, and you encouraged me to use that format when writing new tests. I didn't change all the instances, but these tests caught my eye and felt cleaner without the imports.
This PR is mostly a matter of style and personal taste though, so feel free to disregard it.
> Imports cleanup in unit tests

- pyparsing/core.py
- tests/test_unit.py
I may be missing something, but it seems like the `__req__` and `__rne__` methods defined in core.py aren't built in dundees to override and aren't being used anywhere? I didn't have any success testing them with operators.
> Add misc unit tests for core elements with missing coverage

- examples/romanNumerals.py
There was a bug in the makeRomanNumerals function in romanNumerals.py.  For example, makeRomanNumeral(2) would return 'I', and makeRomanNumeral(3) would return 'II', etc.  This was tracked to an issue within that function that was fixed.  Adding the test for 'MMMMM' caused a test failure with the previous code and now it works.  The 'MMMMM' test was added to the set of tests.
> examples -- romanNumerals -- makeRomanNumeral bug fix, added MMMMM test

- tests/test_unit.py
This class was previously untested so I adapted an example I found on Stack Overflow. It may be worth adding an example to the docstring.
I didn't have any luck exercising the two lines that still aren't covered in a useful way. I was trying to use `GoToColumn().ignore()` but it didn't behave the way I expected it to.
> Add GoToColumn test

- pyparsing/core.py
- tests/test_simple_unit.py
* Add the `ignoreWhitespace()` method, which is the opposite of `leaveWhitespace()` (it sets `skipWhitespace=True`
* Add the argument `recursive=True` to both the above methods, to allow you to control which elements this affects
This closes #203 and helps with some other annoying issues I've been facing.
> Additional configuration for `skipWhitespace` and `leaveWhitespace`

- docs/HowToUsePyparsing.rst
Remove the metod getTokensEndLoc from documentation because no longer exists
> The metod getTokensEndLoc no longer exists

- pyparsing/core.py
Looks like an issue in changing the type of string format used
> Fixing generated default name for QuotedString

- pyparsing/core.py
- tests/test_unit.py
The current behaviour of Keyword.copy unintuitively overrides the identChars of the copied keyword back to the DEFAULT_KEYWORD_CHARS. 
As such:
`
a_keyword = pp.Keyword("test", identChars="_") 
b_keyword = a_keyword.copy() 
`
Match different patterns.
This appears to be either a mistake, or is undocumented.
This pull request removes that override and adds a test to verify.
> Remove identChars override from Keyword.copy

- .travis.yml
- setup.py
- tox.ini
`py39-dev` has been removed in 5811c79597aa718df2e72fb95189233055a2ded3, now the final Python 3.9 version can be used.
> Add Python 3.9 support

- CHANGES
- docs/HowToUsePyparsing.rst
- docs/whats_new_in_3_0_0.rst
- examples/AcManForm.dfm
- examples/booleansearchparser.py
- examples/lucene_grammar.py
- examples/pymicko.py
- examples/pythonGrammarParser.py
- examples/searchparser.py
- examples/simpleArith.py
- examples/snmp_api.h
- pyparsing/diagram/__init__.py
- pyparsing_archive.py
- tests/json_parser_tests.py
- tests/test_unit.py
Found via `codespell -q 3 -L ba,fourty,halp,inout,strng`
> Fix misc. documentation typos

- pyparsing/core.py
- pyparsing/results.py
- pyparsing/testing.py
- pyparsing/util.py
- tests/test_unit.py
This PR adds support for direct and indirect left-recursion, according to the "bounded left-recursion" scheme. This is similar to but neither identical nor directly compatible with Packrat.
Closes #287.
> Left-Recursion support

- docs/HowToUsePyparsing.rst
Looks like these got over-zealously corrected to the new versions.
> Fix old method names in comparison

- CHANGES
- pyparsing/core.py
- tests/test_unit.py
fixes #279 
in addition to unit tests, this change also includes formatting changes to unrelated code that the pre-commit hook required me to do before committing.
My machine says that tests are failing, however it seems to be due to tests that are unrelated to the new changes or new tests that I have added. These tests were failing when i ran the commands to set up the testing environment as suggested in the `tests/README` file and i'm not sure how to properly deal with them since this is my first contribution to this codebase
> add a caseless parameter to the CloseMatch class

- pyparsing/helpers.py
- tests/test_simple_unit.py
- tests/test_unit.py
As discussed in #330, here's a patch to add `max` to `delimited_list`.
A few notes/questions:
- Added `min` in addition to `max`, let me know if you'd rather only have `max`
- Used the names `_min` and `_max` to avoid collision with Python built-ins
- Currently, `delimitedList('A', _max=0)` has the same effect as `delimitedList('A', _max=1)`. Same for `_min=0`/`_min=1`.
Should `_min=0`/`_max=0` raise a `ValueError` instead?
> Added min/max keyword arguments for delimited_list

- examples/booleansearchparser.py
Also updated a few methods to use the snake case version
> Fixing Unicode block range in examples/booleansearchparser.py

- pyparsing/core.py
- tests/test_unit.py
resolves #362
using the same script in that PR:
```console
$ python3 -m prof --best-of 10
0.066
```
> optimize pyparsing import time by deferring regex compile

- setup.py
Packages have to distribute a `py.typed` file in order to signal type checkers that the package is typed (see [PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)).
This file was previously missing though, meaning that downstream users were unable to benefit from pyparsings' type annotations.
> Mark `pyparsing` as a typed package

- docs/whats_new_in_3_0_0.rst
Just a typo in an example code in the [What's New in Pyparsing 3.0.0 - New string constants `identchars` and `identbodychars` to help in defining identifier Word expressions](https://pyparsing-docs.readthedocs.io/en/latest/whats_new_in_3_0_0.html#new-string-constants-identchars-and-identbodychars-to-help-in-defining-identifier-word-expressions), which made the code unrunnable.
Because this is a tiny document change, I don't mind if you merge it or squash it with other commits or do whatever you like.
> Typo in an example code

- pyparsing/core.py
- pyparsing/helpers.py
> No longer use undocumented module "sre_constants"

- pyparsing/core.py
- tests/README.md
- tests/mypy-ignore-cases/forward_methods.py
- tox.ini
The `__lshift__`, `__ilshift__`, and `__or__` methods each return a ParserElement object, but have no annotated return type. The result is that the following code will not type check:
def foo() -> pp.ParserElement:
expr = pp.Forward()
expr <<= bar()
return expr | pp.Literal("baz")
whereas the code will type check if the return line is changed to
return pp.MatchFirst([expr, pp.Literal("baz")])
This is a bug in the types which can be resolved fairly simply with some return type annotations.
Testing is more complicated. Testing annotation accuracy is a relatively novel space with a few options, none of which can be considered standard as of yet.
Many solutions require learning a new toolchain only for that purpose. However, one of the lower-impact options is to use `mypy …
> Fix type annotations of Forward dunder-methods

- .github/workflows/ci.yml
Motivated by #402, these are the changes which I think are needed on the workflow. I've preserved the current testing to the best of my knowledge, but I'm happy to reduce the matrix if desired. (e.g. I'm not sure that `pyparsing_packaging` needs to run on every version.)
If this change is accepted, I can rebase #402 onto this in order to use the matrix config to add a py3.10 `mypy-test` build.
---
When this is used, it means that no new toxenv can be introduced which is incompatible with pypy. This poses an issue for work using mypy to check annotations, as pypy currently cannot install it.
In order to move away from `-e ALL`, expand the github actions matrix config to generate the list of desirable runs. The TOXENV=py setting is used to run the main testenv on the current interpreter, …
> Update CI to avoid `tox -e ALL`

- .github/workflows/ci.yml
- tox.ini
With the updated matrix build config, it's now possible to add a py3.10 build to run `tox -e mypy-test`.
Also, fix a bug in the workflow in on.pull_request.paths
> Enable mypy-test in CI

- pyparsing/core.py
A few docstrings were missing a blank line before lists, causing the start of the list to be parsed by RST as a continuation of the previous line.
> Fix list formatting in docstrings

- docs/HowToUsePyparsing.rst
- pyparsing/core.py
- pyparsing/helpers.py
- pyparsing/results.py
Two warnings remain from the Hebrew and Devanagari names in pyparsing_unicode, but those are due to Sphinx using Python's builtin `re` library to parse identifiers (which does not have thorough Unicode handling for `\w`).
> fix Sphinx errors/warnings

- pyparsing/core.py
- tests/test_unit.py
This turns `Literal()` into a factory which creates an object of the appropriate type from the start, rather than having to overwrite the `__class__` attribute later.
See #412 for the suggestion.
Question: should `Empty` be made a subclass of `Literal`?  It seems to make sense that it would be.
> Use Literal.__new__ to select optimized subclasses

- pyparsing/core.py
- pyparsing/exceptions.py
- pyparsing/helpers.py
- pyparsing/util.py
This allows static type checkers to find and check these functions correctly, and it removes the need to fiddle around with stack frames to get the aliases defined.  (Work on #411.)
> Explicitly declare compatibility alias functions

- pyparsing/core.py
``...`` needs to be surrounded by non-word characters to be detected,
and backslash-space in a non-raw Python string should technically be
written backslash-backslash-space.
> Small docstring formatting/syntax fixes

- pyparsing/core.py
I discovered something more straightforward than what I had in #413 to fix the interactions between `copy.copy()` and a customized `__new__`.  (For info about the `__getnewargs__` method, see the [pickle module](https://docs.python.org/3/library/pickle.html#pickling-class-instances).)
> Simpler fix for __new__ with copy.copy()

- docs/HowToUsePyparsing.rst
Update the documentation for `set_debug` to have the correct variable name of `flag`
> Fix set_debug variable name in documentation

- examples/lucene_grammar.py
Found a variable in the `lucene_grammar.py` example which is not being used, I have removed it to keep things clean
> Removed unused keyword var in lucene_grammar.py

- pyparsing/core.py
Minor fix in the railroad diagram code.  Output wasn't getting the railroad.css styling. Attempts to include using this
```
style = """ # css styling """
...
statement = ....
....
statement.create_diagram("railroad_diagram_demo.html", vertical=6, show_results_names=True, embed=True, head=style)
```
failed.  `railroad_diagram_demo.html` had no styling added except for what was in the template.
Noticed that  `**kwargs` weren't being passed through to the template.
Added `**kwargs` in for the fix.
> Fix railroad so head, body args included in html

- pyparsing/core.py
- pyparsing/diagram/__init__.py
The `head` kwargs wasn't getting passed on the HTML file.  Also the railroad `diagram.diagram.writeStandalone` function adds the default styling to each instance of the diagram this needed to be turned off so that any style sheet include via the `head` arg has an effect.  Fund this while testing.
Sample to test PR
```python
from pyparsing import Word, alphas, restOfLine
salutation = Word(alphas).setResultsName("salutation")
subject = restOfLine.setResultsName("subject")
parse_grammer = salutation + subject
DEFAULT_STYLE = ""
expStyle = """
<style type="text/css">
body {
background-color: blue;
}
.railroad-heading {
font-family: monospace;
color: bisque;
}
svg.railroad-diagram {
background-color: hsl(264,45%,85%);
}
svg.railroad-diagram path {
stroke-width: 3;
stroke: green;
fill: …
```
> Add CSS to Railroad output

- pyparsing/core.py
This should close https://github.com/pyparsing/pyparsing/issues/498.
> Allow `int` or `None` for `cache_size_limit` to `enable_packrat`.

- pyparsing/core.py
- tests/test_unit.py
This is a continuation from the conversation in matplotlib/matplotlib#26152.
I'm opening this here to further the conversation and so we can talk in slightly more concrete terms.
This is based on my last suggestion in that thread where I suggested Forward references without a name do not override the error message.
Either one of these factors or another error message override flag would be sufficient for matplotlib's purposes, so if you feel that this could be broader or would prefer to introduce a more explicit test, then feel free to say so and I will try to do so.
> Limit error message overriding

- pyparsing/helpers.py
It looks like you meant to check both *lpar* and *rpar* here to not be instances of *Suppress*.
> infix_notation: typo checking type of lpar 

- docs/HowToUsePyparsing.rst
**Fix minor render issue in `HowToUsePyparsing.rst`**
**Before:**
> the `-1``th element can be extracted and removed in a single operation using ``pop()`, or any element can be extracted and removed using `pop(n)`
**After:**
> the last element can be extracted and removed in a single operation using `pop()`, or any element can be extracted and removed  using `pop(n)`
> Minor update to HowToUsePyparsing.rst

- pyparsing/actions.py
- pyparsing/core.py
- pyparsing/exceptions.py
- pyparsing/helpers.py
- pyparsing/util.py
* When using the `replaced_by_pep8` decorator with a different method signature for simplicity, as the real signature is generated by the decorator, some static checkers might find false positive errors when calling pyparsing code (see issue #501).
* Refactor the calls for the compatibility code to not use the `replaced_by_pep8` decorator but calling directly the `_make_synonym_function` function to generate the synonym methods/functions.
* This way the signature of the method/function is automatically copied and the static checkers will not report false positives.
> Fix pep8 compatibility code (fixes #501)

- pyparsing/core.py
> Code refactoring/denesting for core.py

- pyparsing/core.py
> Avoid assigning an empty error message to delegated parse exception

- docs/HowToUsePyparsing.rst
- pyparsing/common.py
- tests/test_unit.py
I was working on parsing numerical data and found that none of pyparsing's numerical expressions support the non-finite floating point values (NaN, +Inf, and -Inf).
Just based on the implementation, `ppc.fnumber` looks like a reasonable place to add support for this, since it's independent of the other numerical expressions and has the float conversion baked in. (Indeed, I initially thought it would accept these values due to the "float" part.) Essentially, this PR makes `fnumber` match anything that Python's `float` can itself parse. [cPython's parsing](https://github.com/python/cpython/blob/main/Python/pystrtod.c#L28) is fully case-insensitive and accepts (optionally signed) "NaN", "Inf", and "Infinity".
One note of caution would be if users somehow rely on `fnumber`'s failure to parse …
> Accept floating-point NaN and Inf as fnumber

- examples/eval_arith.py
Found a small confusing inaccuracy in the examples
> Fix typo in examples

- pyparsing/core.py
fixes
```
Type of "set_parse_action" is partially unknown
Type of "set_parse_action" is "(*fns: (() -> Any) | ((ParseResults) -> Any) | ((int, ParseResults) -> Any) | ((str, int, ParseResults) -> Any), **kwargs: Unknown) -> ParserElement"Pylance[reportUnknownMemberType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownMemberType)
```
and similar for other methods in ParserElement
> annotate ParserElement kwargs

- .github/workflows/ci.yml
- pyparsing/core.py
The second commit should fix the problem, **but** right now it won't work since pyparsing 3.1.3 is still out there. Tox fails before even running the code from this repo: https://github.com/felixfontein/pyparsing/actions/runs/10546308170/job/29217617943?pr=1
(I've a mirror PR of this in my fork where I don't have to wait for CI to be approved: https://github.com/felixfontein/pyparsing/pull/1)
> Add Python 3.6 to CI

- pyparsing/exceptions.py
A bit of a silly change, feel free to close if you don't accept these.
I have moved the logic of the "found" string out of the `__str__` magic method. This allows the user to generate prettier messages from the exception. I also think it's a bit cleaner to avoid parsing logic in `__str__`
From the following exception
```Python
In [2]: Keyword("KEY1").parse_string("KEY2", parseAll=True)
---------------------------------------------------------------------------
ParseException                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 Keyword("KEY1").parse_string("KEY2", parseAll=True)
File ~/Documents/pyparsing/pyparsing/core.py:1197, in ParserElement.parse_string(self, instring, parse_all, parseAll)
1194         raise
1195     else:
1196         # catch and …
```
> Add found string as property

- pyparsing/helpers.py
Improve performance of the `cpp_style_comment` helper by rewriting it as a single `Regex`.
This change leads to very significant performance improvements when parsing grammars that use `.ignore(cpp_style_comment)`.
> Improve performance of cpp_style_comment

- pyparsing/common.py
Non-capturing groups are faster to parse and IMO show the intent better. Also, the `(?i:...)` inline flag in this format does not need to be at the beginning of the regular expression, allowing for the pattern to be easily reused as part of other custom `Regex`es (e.g. by extracting it as `pyparsing.common.ieee_float.re.pattern`—not sure you want to encourage this, but TBF I'm doing something like this in my own project that uses this library).
> Use non-capturing groups in common.fnumber and common.ieee_float

- examples/simpleArith.py
I think it's appropriate to use the names you've defined for the operators "!" nad "^" in place of their literals.
> Fix a typo and two unused names

- pyparsing/exceptions.py
This is incredibly minor, but... the example output in `ParseException`'s docstring had gotten out-of-date / at odds with reality. Fixed.
> Docs: Update ParseException's docstring example

- docs/whats_new_in_3_2.rst
The mention of `complex_chemical_formulas.py` being included "to add parsing capability for formulas such as..." was followed by a string of line-noise that looked nothing like a chemical formula, and was clearly not UTF-8 text or anything close to it. Replace with real UTF-8 from the actual source file.
> Docs: Correct encoding damage in What's New 3.2

- pyparsing/actions.py
- pyparsing/core.py
- pyparsing/diagram/__init__.py
- pyparsing/exceptions.py
- pyparsing/results.py
- pyparsing/util.py
Dunder init methods return None, which seems pretty obvious and easily inferred, but unless they're annotated that way, running `mypy --strict` will complain. (Including in external subclasses.)
Background/motivation:
A PR updating the `pydot` parser (pydot/pydot#451) adds a subclass of `pyparsing.core.Token` of the form:
```python
import typing as T
from pyparsing import Token
def HTML(Token):
def __init__(self) -> None:
super().__init__()
def parseImpl(
self, instring: str, loc: int, do_actions: bool = True
) -> T.Tuple[int, str]:
```
Surprisingly, when running `mypy --strict` on the code, it produces this error unless a `# type: ignore` is added to the line with the `super()` call.
```text
src/pydot/dot_parser.py: note: In member "__init__" of class "HTML":
src/pydot/dot_parser.py:390: …
```
> Add return type annotations to __init__ methods

- docs/whats_new_in_3_2.rst
Just a very small thing I noticed while reading the rendered docs at RTD. The space makes sure the inline code block is terminated after `base_1` and therefore avoids rendering the entire sentence up to `loc` as a code section.
I wasn't sure which delineation was intended, so I kept the code as-is and just added the space. There is an alternative to include the `=False` in the code section as well:
```diff
- using ``with_line_numbers`` inside a parse action, set ``base_1``=False, since the
+ using ``with_line_numbers`` inside a parse action, set ``base_1=False``, since the
```
If the alternative is desired, I can quickly push that up instead. :+1:
Edit: The odd formatting can currently be seen [here](https://pyparsing-docs.readthedocs.io/en/latest/whats_new_in_3_2.html#additional-api-chang …
> Fix inline code missing space for termination

- pyparsing/core.py
Looking at adjusting the pydot GraphViz parser's handling of quoted strings, I was rather surprised to discover an unexpected interaction in the `QuotedString` parameters:
As implemented in `QuotedString`, `convert_whitespace_escapes` **has no effect** unless `unquote_results` is set to `True`. 
This PR adds a Caution admonition to the API documentation, advising users of this restriction.
> QuotedString: Add caution about param interactions

- docs/_static/pyparsing.css
A minor fix to the custom CSS for versionadded / versionmodified directives, so that they line up properly when wrapped.
> Docs: Account for wrapping in CSS

- CONTRIBUTING.md
- docs/CONTRIBUTING.md
- docs/conf.py
- docs/index.rst
- docs/requirements.txt
I'm planning to add a section to the `CONTRIBUTING.md` file about writing doctests for Pyparsing, and as I was doing that thought that it would make sense to make it part of the official documentation as well. So, this PR does that, which involves:
- Enable the `myst_parser` Python package as a Sphinx extension, which enables it to include MarkDown files in the documentation.
- Add `myst_parser` to `docs/requirements.txt` so that it's installed by ReadTheDocs and anyone else looking to build documentation.
- Symlink `CONTRIBUTING.md` into the `docs/` dir (this needs to be tested against ReadTheDocs; it may or may not work)
- Add `CONTRIBUTING` to the `index.rst` toctree.
- Update the title from "CONTRIBUTING" to "Contributing to Pyparsing".
That way, the content is included in the project …
> Add CONTRIBUTING doc to documentation

- CONTRIBUTING.md
- docs/Writing_Doctests.rst
- docs/conf.py
- docs/index.rst
- docs/pyparsing.rst
- docs/whats_new_in_3_1.rst
- pyparsing/__init__.py
- pyparsing/actions.py
- pyparsing/common.py
- pyparsing/core.py
- pyparsing/diagram/__init__.py
- pyparsing/exceptions.py
- pyparsing/helpers.py
- pyparsing/results.py
- pyparsing/testing.py
- pyparsing/util.py
This PR does a _lot_. The broad strokes:
1. Convert all documentation examples to [doctests](https://docs.python.org/3/library/doctest.html#module-doctest) which can be tested for syntax issues and correct output
2. Add comprehensive documentation on writing doctests to the online docs (new chapter "Writing doctest examples")
3. Restore the Sphinx "Alabaster" theme, but with a (classic-style) local table-of-contents for the API documentation
Not done, yet:
1. Add any Spinx `make doctest` runs to CI or ReadTheDocs configuration.
2. Fix the one failing doctest (details at https://github.com/pyparsing/pyparsing/issues/608#issuecomment-3058546453)
> Documentation: Convert examples to doctests, restore Alabaster theme
