- .travis.yml
This PR add Travis CI config so all pushes can be tested. This is especially useful to see _before merge_ if future pull requests break tests or not.
Here's an example: https://travis-ci.org/hugovk/pyparsing/builds/414068785
Note Python 3.7 needs slightly different config, see https://github.com/travis-ci/travis-ci/issues/9069 for details.
TODO by this repo's owner:
1. Create a free [Travis CI](https://travis-ci.org) account
2. Enable this repo at https://travis-ci.org/profile (you may need to <i>Sync account</i> first)
3. Merge this PR or make a new PR or push
> Run unit tests on Travis CI

- README.md
Adds colouring to the code block:
> README: Use Python code formatting

- setup.py
Fixes https://github.com/pyparsing/pyparsing/issues/7.
> Update url and download_url

- pyparsing.py
- unitTests.py
Resolves the infinite recursion potential by setting a temporary name during resolution.
> Descriptive names for Forward expressions

- examples/bigquery_view_parser.py
A parser to extract table names from the SQL for a BigQuery view.  Given the SQL of a view, it returns information about the tables that are being selected from.
> Example BigQuery view SQL parser

- examples/protobuf_parser.py
Hey, tried to use this example on proto3 syntax and got a problem. Hope this fix will be useful for somebody.
Regarding to: https://developers.google.com/protocol-buffers/docs/proto3
> Update example protobuf to proto3 syntax

- examples/SimpleCalc.py
- examples/fourFn.py
- examples/htmlStripper.py
- examples/protobuf_parser.py
- examples/sexpParser.py
- examples/simpleSQL.py
- examples/urlExtractorNew.py
- pyparsing.py
- unitTests.py
Discovered using the command:
flake8 --select F401 .
> Remove unused imports

- tests/test_unit.py
Available since Python 2.4.
https://docs.python.org/3/library/functions.html#staticmethod
> Use staticmethod decorator

- tests/test_unit.py
Available since Python 2.4.
https://docs.python.org/3/library/functions.html#classmethod
> Use classmethod decorator

- pyparsing/core.py
- tests/test_unit.py
I'd appreciate any feedback or edits! I have a feeling some of them could be better located in the file. I've tried to create simple examples for these tests but if they don't capture the intent and there are suggestions to rework them, I'm happy to do it.
> Add unit tests to expand test coverage

- examples/eval_arith.py
It seems this example was not failing if there was a problem
> ensure test can fail

- pyparsing/core.py
- pyparsing/helpers.py
- tests/test_unit.py
Minor changes intended to make the test code leaner and correct some documentation typos
> Housekeeping

- docs/HowToUsePyparsing.rst
- docs/_static/json.html
- pyparsing/diagram/__init__.py
- pyparsing/diagram/template.jinja2
- tests/test_diagram.py
- Add diagram documentation
- Add more diagram tests
- Allow more customization of diagram generation
> Railroad Diagram Improvements

- README.rst
I updated the [`README.rst`](https://github.com/pyparsing/pyparsing/blob/master/README.rst) file with a better design.
> Update documentation design

- pyparsing/helpers.py
- tests/test_simple_unit.py
https://github.com/pyparsing/pyparsing/issues/284
> Add allowTrailingDelim to delimitedList helper

- pyparsing/exceptions.py
> Don't import Optional from typing, import the whole module.

- pyparsing/core.py
> Return NotImplemented for unsupported operations

- examples/inv_regex.py
PEP8 update of invRegex example I converted for some experiments. Figured I'd make a PR for it.
-Ross
> Update and rename invRegex.py to inv_regex.py

- .github/workflows/ci.yml
Closes #471
Example of success run https://github.com/joycebrum/pyparsing/actions/runs/4409373880
> Set minimal permissions to ci.yml

- pyparsing/common.py
* Fix one occurrence of setName that was not converted to the pep8-compliant names.
> Use pep8 version of method set_name

- .github/workflows/ci.yml
> ci: add Python 3.12 to test matrix

- pyparsing/results.py
- range_check.html
> Minor code refactoring/denesting for results.py

- pyparsing/core.py
- pyparsing/exceptions.py
- pyparsing/helpers.py
- pyparsing/testing.py
- pyparsing/unicode.py
> Code refactoring for other files
